# Generated by Django 4.1.7 on 2023-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField(blank=True, max_length=300, null=True)),
                ("covers", models.IntegerField(default=1)),
                ("date_opened", models.DateField()),
                ("date_closed", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("manager", models.CharField(max_length=50)),
            ],
        ),
    ]
