# Generated by Django 4.1.7 on 2023-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0003_alter_shop_date_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="tel_main",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="tel_man",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
